spring:
  datasource:
    url: jdbc:h2:mem:sigavt;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  data:
    seed-on-startup: true
